<?php
return array (
  'view_ori_pic' => '查看大圖',
  'turn_left' => '向左轉',
  'turn_right' => '向右轉',
  'ori_repost' => '原文轉發',
  'ori_comment' => '原文評論',
  'delete' => '刪除',
  'repost' => '轉發',
  'comment' => '評論',
  'report' => '舉報',
  'fav' => '收藏',
  'from' => '來自',
  'emotion_show' => '表情預覽',
  'create_tag' => '+加標籤',
  'taglist' => '標籤：',
  'publish_all' => '公開-你發表的微博可以被大家公開查看哦',
  'publish_to_me' => '私密-發表的微博只有自己才能看到',
  'publish_to_me_no_report' => '該條為私密微博，無法轉發',
  'publish_to_closefriends' => '此微博被作者設置為僅密友可見',
  'publish_closefriends_no_report' => '該條為僅密友可見微博，無法轉發',
  'collect' => '採集',
  'attitude' => '表態',
);
