<?php
$lang['disable_show'] = "顯示錯誤，請稍後再試。";
$lang['system_error'] = "系統繁忙，請稍候再試吧。";
$lang['operate_failed'] = "操作失敗";
$lang['repeated'] = "不要貪心哦，相同內容的東西髮一次就夠啦。";
$lang['law_not_allow'] = '抱歉，此內容違反了<a target="_blank" href="http://weibo.com/z/guize/guiding.html">《新浪微博社區管理規定(試行)》</a>或相關法規政策，無法發佈。如需幫助，請聯繫<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">微博客服</a>';
$lang['not_follow'] = '你還沒有關注此用戶';
$lang['remark_self'] = '不能為自己設置備註名哦';
//系统错误码： 此处的报错都以当前行为操作作为报错提醒文案；
$lang['submit_failed'] = '提交失敗';
$lang['load_failed'] = '加载失败';
$lang['rumor_not_repost'] = '抱歉，此內容違反了相關法律法規要求，無法發佈。<a target="_blank" href="http://help.weibo.com/faq/q/676/12574#12574">查看詳情</a>，如需幫助，<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">請聯繫客服</a>';
$lang['rumor_not_cmt'] = '抱歉，此內容違反了相關法律法規要求，無法發佈。<a target="_blank" href="http://help.weibo.com/faq/q/676/12574#12574">查看詳情</a>，如需幫助，<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">請聯繫客服</a>';
$lang['feed_block_repeat'] = "已經屏蔽了該用戶";
$lang['feed_block_error'] = "屏蔽失敗";
$lang['feed_block_succ'] = '屏蔽成功';
$lang['feed_block_error_no_followed'] = "您尚未關注此用戶，屏蔽失敗";
$lang['feed_block_error_max_numm'] = "已經達到屏蔽上限。";
$lang['visible_not_repost'] = '抱歉，不能轉發帶顯示權限的微博';
$lang['visible_not_comment'] = '抱歉，你還沒有評論該微博的權限';
$lang['error_params'] = "你提交的內容格式不正確。" ;
$lang['over_length'] = "糟糕，小秘書數錯數啦，刪掉幾個字試試吧。";
$lang['feed_mid_filtered'] = "隱藏成功";
$lang['filtered_sina_app'] = "該來源暫時不可屏蔽哦。<a href='http://weibo.com/zt/s?k=9286'>我要提建議。</a>";
$lang['filter_app_repeat'] = "已經屏蔽了該應用";
$lang['filter_mid_repeat'] = "已經隱藏了該條微博";
$lang['filter_repeat'] = "已經添加了該屏蔽";
$lang['filter_sina_app'] = "不能屏蔽新浪應用";
$lang['error_create_jxj'] = "最多可創建20個精選集，你已達到上限嘍~" ;
$lang['error_name_exists'] = "﻿您已經有一個相同名字的精選集啦，﻿為你的寶貝兒再起一個名字吧~" ;
$lang['error_verification'] = '抱歉，請先綁定手機領取“微身份”勳章，帳號更安全。或可繼續瀏覽微博。';
$lang['error_location'] = 'http://weibo.com/z/vshenfen/';
$lang['error_OKText'] = '馬上領取';
$lang['error_cancelText'] = '取消';
$lang['error_OKSuda'] = 'key=tblog_identify_stripe&value=badge_apply';
$lang['error_cancelSuda'] = 'key=tblog_identify_stripe&value=identify_cancel';
$lang['error_mblogcard_failed'] = '獲取失敗！';
$lang['error_mblogcard_none'] = '此微博已不存在！';
return $lang;