<?php
return array (
		'remail_type_word' => '請文明發言，還可以輸入<span>140</span>字',
		'recommend_topic' => '推薦話題：',
		'smiley' => '表情',
		'pic' => '圖片',
		'video' => '視頻',
		'music' => '音樂',
		'topic' => '話題',
		'vote' => '投票',
		'publish'=>'發佈微博按鈕',
		'textarea_title' => '微博輸入框',
		'feed_list' => '微博內容列表',
		'event' =>'活動',
		'descface'=>'通過它來傳遞情感心情，讓微博發表更有趣',
		'descimage'=>'有圖有真相，發表更真實',
		'descviedo'=>'有什麽新鮮事，視頻來直播',
		'descmusic'=>'添加一首歌，讓發表更動聽',
		'desctopic'=>'參與當前最熱話題',
		'descvote'=>'幫你表達和收集意見與建議',
		'descactive' =>'快速、便捷組織活動',
		'more'=>'更多',
		'actiontitle' => '查看來源',
		'feed_all' => '公開',
		'feed_me_to_see' => '私密',
		'feed_me_follow' => '我關注的人',
		'feed_my_friend' => '雙向關注',
		'publish_to_group' => '發到圍群',
		'publish_all' => '公開-你發表的微博可以被大家公開查看哦',
		'publish_to_me' => '私密-發表的微博只有自己才能看到',
		'weigongyi' => '微公益',
		'descweigongyi' => '以微薄之力 讓世界更美',
		'weiba'=>'微吧',
		);