<?php
return array(
'person_page' => '個人主頁',
'home_page' => '首頁',
'mentions_me' => '提到我的',
'my_comment' => '評論',
'my_message' => '私人訊息',
'my_fav' => '收藏',
'album' => '相冊',
'music' => '微音樂',
'event' => '活動',
'vote'=> '投票',
'admin_list' => '管理列表',
'more' => '更多',
'star' => '名人堂',
'top' => '風云榜',
'topic' => '微話題',
'talk' => '微訪談',
'radio' => '微電台',
'live' => '微直播',
'topmblog' => '熱門微博',
'screen' => '大屏幕',
'edit' => '添加',
'setting' => '設置',
'default_badge_intro' => '發言即可獲此勳章',
'mic_data' => '微數據',
'show' => '微秀',
'handpick' => '微博精選',
);