<?php
$lang['change_name'] = "改名为";
$lang['followed'] = "关注了";
$lang['deng'] = "等%1%人";
$lang['people'] = "人";
$lang['change_template'] = "更换了新模版";
$lang['try'] = "我也要试试»";
$lang['change_photo'] = "更换了头像";
$lang['who_photo'] = "%1%的新头像";
$lang['look'] = "去看看»";
$lang['like'] = "喜欢";
$lang['_photo'] = "的照片";
$lang['come_from'] = "来自于";
$lang['upload_photo'] = "上传了%s张照片到";
$lang['in_album'] = "在相册";
$lang['tag_people'] = "中圈出了";
$lang['from'] = "来自";
$lang['more'] = "查看更多";
$lang['no_activities'] = "你关注的人还没有动态哦。推荐你去<a href='/f/find'>找人</a>have a try ";
return $lang;