<?php
$lang = array(
	'whisper_follow' => '想默默關注一個人，<span class="z_sp">不希望</span>其他人知道？',
	'view_quietfollow_mblog' => '去看看他們最近在說什麼' ,
	'whisper_he_now' => '現在你可以悄悄關注他',
	'whisper_by_you' => '被你悄悄關注的人：',
	'cant_be_recomand'=>'不會收到新粉絲提醒' ,
	'not_in_his_fans'=>'粉絲列表內不會顯示你',
	'no_one_knews' => '其他人看你的粉絲列表，不會顯示他',
	'how_to_whisper' => '如何悄悄關注他：',
	'input_nick_up' => '你可以在上方的輸入框內，輸入對方的暱稱，直接悄悄關注他' ,
	'go_his_profile' => '還可以到他的微博頁，那裡也可以悄悄關注他',
	'you_whisper_follow' => '我悄悄關注了' ,
	'person'	=> '人 ',
	'person_max' => '最多10人',
	'member_level' => '您當前是',
	'member_quite' => '可悄悄關注%s人',
	'add_follow_to_group' => '將關注人添加到分組：',
	'add'	=> '添加',
	'input_nick' => '請輸入想要悄悄關注用戶的暱稱',
	'quit_private_att' => '取消悄悄關注',
	'quiet_follow' => '悄悄關注：',
	'i_know' => '知道了',
);
return $lang ;