<?php
define('APP_FACE', 500); //表情
define('APP_IMAGE', 501); //图片
define('APP_VIEDO', 502); //视频
define('APP_MUSIC', 503); //音乐
define('APP_TOPIC', 504); //话题
define('APP_VOTE', 5); //投票
//define('APP_EVENT',3);//活动
define('APP_WEIGONGYI', 14); //微公益
define('APP_WEIBA', 17); //微吧

$third_api_conf = array(
    APP_FACE => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.smiley"), //标题
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.smiley"), //名称
        'class' => 'face', //class名称
        //'feedclass' => '', feed解析的样式 如果feed需要相关的icon样式，请将该配置参数加上
        'actiontype' => 'face', //发布器的nodetype
        'tabindex' => '3', //发布器的tabindex
        'rendurl' => '', //feed展开请求地址
        'interactiveurl' => '', //发布器请求及feed交互地址
        'sudakey' => '', //suda的key
        'sudavalue' => '', //suda的value
        'publishshow' => false, //是否属于发布器上是否显示
        'feedshow' => false, //feed解析使用
        'defaultshow' => true, //是否默认发布器上显示
        'defaultchooseshow' => true, //如果用户没有选择和排序选择
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descface"), //文案
    ),
    APP_IMAGE => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.pic"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.pic"),
        'class' => 'img',
        'actiontype' => 'image',
        'tabindex' => '3',
        'rendurl' => '',
        'interactiveurl' => '',
        'sudakey' => '',
        'sudavalue' => '',
        'publishshow' => false,
        'feedshow' => false,
        'defaultshow' => true,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descimage"),
    ),
    APP_VIEDO => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.video"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.video"),
        'class' => 'movie',
        'actiontype' => 'video',
        'tabindex' => '3',
        'rendurl' => '',
        'interactiveurl' => '',
        'sudakey' => '',
        'sudavalue' => '',
        'publishshow' => true,
        'feedshow' => false,
        'defaultshow' => true,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descviedo"),
    ),
    APP_MUSIC => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.music"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.music"),
        'class' => 'music',
        'actiontype' => 'music',
        'tabindex' => '3',
        'rendurl' => '',
        'interactiveurl' => '',
        'sudakey' => '',
        'sudavalue' => '',
        'publishshow' => true,
        'feedshow' => false,
        'defaultshow' => true,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descmusic"),
    ),
    APP_TOPIC => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.topic"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.topic"),
        'class' => 'topic',
        'actiontype' => 'topic',
        'tabindex' => '3',
        'rendurl' => '',
        'interactiveurl' => '',
        'sudakey' => '',
        'sudavalue' => '',
        'publishshow' => true,
        'feedshow' => false,
        'defaultshow' => true,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.desctopic"),
    ),
    APP_VOTE => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.vote"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.vote"),
        'actiontitle' => Comm_I18n::text("tpls.pl.content.publishertop.actiontitle"),
        'class' => 'vote',
        'feedclass' => 'feedico_vote',
        'actiontype' => 'vote',
        'tabindex' => '3',
        'rendurl' => 'http://vote.i.t.sina.com.cn/openapi/votes/render/show',
        'interactiveurl' => 'http://vote.i.t.sina.com.cn/openapi/votes/render/show',
        'sudakey' => '',
        'sudavalue' => '',
        'publishshow' => true,
        'feedshow' => true,
        'defaultshow' => true,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descvote"),
    ),
    /**
      APP_EVENT => array(
      'title' =>Comm_I18n::text("tpls.pl.content.publishertop.event"),
      'name'	=>Comm_I18n::text("tpls.pl.content.publishertop.event"),
      'class'	=>'',
      'actiontype'=>'plugin',
      'tabindex'=>'3',
      'rendurl'=>'http://i.event.weibo.com/feedcreate',
      'interactiveurl'=>'http://i.event.weibo.com/feedcreate',
      'sudakey'=>'',
      'sudavalue'=>'',
      'publishshow'=>true,
      'feedshow'=>false,
      'defaultshow'=>false,
      'defaultchooseshow'=>true,
      ),
     */
    APP_WEIGONGYI => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.weigongyi"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.weigongyi"),
        'class' => 'gongyi',
        'feedclass' => 'W_ico16 icon_sw_welfare',
        'actiontype' => 'plugin',
        'tabindex' => '3',
        'log' => 'weigongyi',
        'rendurl' => 'http://i.new.gongyi.weibo.com/getfeeddata?version=v4',
        'interactiveurl' => 'http://i.new.gongyi.weibo.com/gongyiact?version=v4 ',
        'sudakey' => 'feedgongyi',
        'sudavalue' => 'feedshow',
        'publishshow' => true,
        'feedshow' => true,
        'defaultshow' => false,
        'defaultchooseshow' => true,
        'desctext' => Comm_I18n::text("tpls.pl.content.publishertop.descweigongyi"),
    ),
    APP_WEIBA => array(
        'title' => Comm_I18n::text("tpls.pl.content.publishertop.weiba"),
        'name' => Comm_I18n::text("tpls.pl.content.publishertop.weiba"),
        'class' => '',
        'feedclass' => 'feedico_bar',
        'actiontype' => 'plugin',
        'tabindex' => '3',
        'log' => '',
        'rendurl' => 'http://i.weiba.weibo.com/weibofeed/show',
        'interactiveurl' => 'http://i.weiba.weibo.com/weibofeed/addcomment',
        'sudakey' => 'weiba_feed_analyze',
        'sudavalue' => 'feed_unfold',
        'preimgsudakey' => 'weiba_feed_analyze',
        'preimgsudavalue' => 'feed_unfold',
        'publishshow' => false,
        'feedshow' => true,
        'defaultshow' => false,
        'defaultchooseshow' => false,
        'desctext' => '',
    ),
    34 => array(
        'title' => "新浪新闻",
        'name' => "新浪新闻",
        'class' => "",
        'feedclass' => "W_ico16 icon_sw_bar",
        'actiontype' => "plugin",
        'tabindex' => "3",
        'log' => "sinanews",
        'rendurl' => "http://i.platform.sina.com.cn/news/get_feed_detail?app_key=1273075414",
        'interactiveurl' => "",
        'sudakey' => "tblog_feed_analyze",
        'sudavalue' => "news_link",
        'preimgsudakey' => "tblog_feed_analyze",
        'preimgsudavalue' => "news_narrow_figure",
        'publishshow' => "",
        'feedshow' => true,
        'defaultshow' => "",
        'defaultchooseshow' => "",
        'desctext' => "",
    ),
    31 => array(
        'title' => "微什么",
        'name' => "微什么",
        'actiontitle' => "查看来源",
        'class' => "",
        'feedclass' => "W_ico16 icon_sw_what",
        'actiontype' => "",
        'tabindex' => "",
        'log' => "vote",
        'rendurl' => "http://ask.weibo.com/aj/askwb/renderfeed.php",
        'interactiveurl' => "http://i.platform.sina.com.cn/weishenme/ansfeed?app_key=1760263216",
        'sudakey' => "",
        'sudavalue' => "",
        'publishshow' => 0,
        'feedshow' => true,
        'defaultshow' => 0,
        'defaultchooseshow' => 0,
        'desctext' => "",
    ),
    25 => array(
        'interactiveurl' => 'http://sl.biz.weibo.com/slfront/slref'
    ),
    34 => array(
        'title' => "新浪新闻",
        'name' => "新浪新闻",
        'class' => "",
        'feedclass' => "W_ico16 icon_sw_bar",
        'actiontype' => "plugin",
        'tabindex' => "3",
        'log' => "sinanews",
        'rendurl' => "http://i.platform.sina.com.cn/news/get_feed_detail?app_key=1273075414",
        'interactiveurl' => "",
        'sudakey' => "tblog_feed_analyze",
        'sudavalue' => "news_link",
        'preimgsudakey' => "tblog_feed_analyze",
        'preimgsudavalue' => "news_narrow_figure",
        'publishshow' => "",
        'feedshow' => true,
        'defaultshow' => "",
        'defaultchooseshow' => "",
        'desctext' => "",
    ),
    33 => array(
        'title' => "微刊",
        'name' => "微刊",
        'class' => "",
        'feedclass' => "W_ico16 icon_sw_wkan",
        'actiontype' => "",
        'tabindex' => "3",
        'log' => "sinanews",
        'rendurl' => "http://kan.i.weibo.com/feedanalyze/render",
        'interactiveurl' => "http://kan.i.weibo.com/feedanalyze/render",
        'sudakey' => "tblog_feed_analyze",
        'sudavalue' => "kan_narrow_figure",
        'preimgsudakey' => "",
        'preimgsudavalue' => "",
        'publishshow' => "",
        'feedshow' => true,
        'defaultshow' => "",
        'defaultchooseshow' => "",
        'desctext' => "",
    ),
    26 => array(
        'title' => "APP",
        'name' => "APP",
        'class' => "",
        'feedclass' => "W_ico16 icon_sw_apps",
        'actiontype' => "",
        'tabindex' => "3",
        'log' => "sinanews",
        'rendurl' => "http://i2.api.weibo.com/2/proxy/apps/feedapp/gethtml.json?v=5",
        'interactiveurl' => "http://i2.api.weibo.com/2/proxy/apps/feedapp/gethtml.json?v=5",
        'sudakey' => "",
        'sudavalue' => "",
        'preimgsudakey' => "",
        'preimgsudavalue' => "",
        'publishshow' => "",
        'feedshow' => true,
        'defaultshow' => "",
        'defaultchooseshow' => "",
    ),
);
return $third_api_conf;
?>
