<?php 
return array(
'same_topic' => '你们有相同话题',
'same_area' => '你们可能在同一地区',
'same_tag' => '你们有相同标签',
'same_school' => '你们在同一学校',
'same_company' => '你们在同一公司',
'same_ip' => '可能离你很近',
'msn_buddy' => '可能是MSN联系人',
'mail_contact' => '可能是邮箱联系人',
'no_interest' => '不感兴趣',
'my_att_list' => '我关注的人中',
'my_fri_list' => '我的好友中',
'we' => '我们有',
'weare'=>'我们是',
'fri_att' => '个共同好友',
'indirect_att' => '个间接关注人',
'etc' => '等',
'total' => '共',
'atted_other_he' => '人也与他互相关注',
'atted_he' => '人也关注了他',
'atted_other_she' => '人也与她互相关注',
'atted_she' => '人也关注了她',
'att' => '加关注',
'colleague'=>'同事',
'classmate'=>'同学',
'collage'=>'大学',
'juschool'=>'小学',
'midschool'=>'初中',
'hishcool'=>'高中',
'techschool'=>'中专技校',
);