<?php
$lang['look'] = '去看看';
$lang['yes'] = '知道了';
$lang['group'] = '我們調整了分組的位置，在這裏可以按分組查看微博更新哦';
$lang['template'] = '新版微博模板全新升級，全面支持自定義配色、推薦模板配色給力升級，去換個模板試試吧。';
$lang['forward'] = '新版微博支持查看轉發記錄了，快來看看吧。';
$lang['comment'] = '新版微博評論裏@也能提醒了，不再漏過一次互動';
$lang['music'] = '發照片，聽音樂，讓你的微博生活多姿多彩';
$lang['versions'] = '點擊“帳號”中<strong>“版本選擇”</strong>進行“兩欄”和“三欄”的版本切換。快來體驗不同版本吧！';
$lang['search'] = '新版微搜索更好用啦！找微博、找人、找微羣、找應用，一搜百應！';
$lang['tips_content'] = '評論、私信加強隱私設置選項啦。保護隱私防騷擾，更加hold住。 <a href="http://account.weibo.com/settings/privacy" action-type="iKnow"  action-data="type=link&bubbletype=4&time=604800">立即查看»</a>';
$lang['tips_comment'] = '<a href="http://service.account.weibo.com/" target="_blank">新浪微博社區管理中心舉報處理大廳，歡迎查閱！</a>';
$lang['tips_whisper'] = "悄悄關注他，只有你自己知道哦。" ;
$lang['daren_apply'] = '立即申請>>';
$lang['tips_close'] = '關閉';
$lang['private_group'] = '私密群，小圈子實時分享快樂。' ;
$lang['vote'] = '投票官方形象誕生，小態度大力量！' ;
$lang['wei_event'] = '隨手拍年味，即得龍年勳章！' ;
$lang['music'] = '“喜歡的歌”，一目了然！' ;
$lang['mood_tips'] = '春節過得爽不爽？曬曬你的心情吧';
$lang['comment_talk'] = '評論列表中可以查看對話啦！';
$lang['pub_mood_notice1'] = '今天心情怎麼樣？別忘了記上一筆，跟大家分享吧。';
$lang['pub_mood_notice2'] = '最近心情如何？寫心情是好習慣，一定要保持哦。';
$lang['pub_mood_notice3'] = '寫心情，從今天開始，填滿這個月的心情日曆吧。';
$lang['identify'] = '領取“微身份勳章”，做個可靠的人，帳號更安全，微博交流更放心。';
$lang['fetch'] = '現在領取';
$lang['tips_at_lenovo'] = '輸入@可以選擇最近聯繫人了';
return $lang;
