<?php
return array (
  'title' => '我的通知',
  'list_count' => '共%s條',
  'list_total' => '共%s個應用',
  'all_expand' => '全展開',
  'all_unexpand' => '全收起',
  'expand' => '展開',
  'list_none' => '你目前還沒有通知！',
  'setnotice' => '設置通知提醒',
  'feedback' => '意見反饋',
  'fold' => '收起',
  'new_notice' => '新通知' ,
  'shield_notice' => '屏蔽' ,
  'view_all' => '查看全部' ,
  'notice_unit' => '條' ,
  'sys_notice'=>'系統通知',
  'best_friend_notice'=>'密友通知' ,
  'fold_notice' =>'收起全部',
	'notice_manage'	=>'通知管理',
	'block_apps' =>'已屏蔽應用',
	'unshield_notice' => '解除屏蔽',
	'shield_title'=> '屏蔽後，將不再接收 %s 發來的通知',
    'shield_21632'=> '你已經取消對該應用的授權，將不會收到它發出的通知',
    'shield_21635'=> '不可以屏蔽該應用發的通知',
    'shield_21631'=> '你屏蔽的應用太多了，暫時不可以屏蔽該應用',
    'shield_21633'=> '該應用已不再具有通知發送權限',
    'shield_21634'=> '你已經屏蔽過該應用了',
	'no_block_apps'=> '还没有被屏蔽的应用',
	'rest_count'=> '還有%s個，點擊查看',
	'more'=> '更多'
);