<?php
return array (
  'do_add_mblog' => '發微博',
  'do_set_remark' => '設置備註',
  'do_send_msg' => '發私信',
  'do_set_list' => '設置分組',
  'lbl_company' => '公司：',
  'lbl_school' => '大學：',
  'lbl_blog' => '博客：',
  'txt_blocked' => '已加入黑名單',
  'txt_unblock' => '解除',
  'txt_bilateral' => '互相關注',
  'do_cancel' => '取消',
  'txt_hasfollowed' => '已關注',
  'txt_add_follow' => '加關注',
  'do_add_block' => '加入黑名單',
  'do_recommend' => '推薦給朋友',
  'txt_for' => '為',
  'do_introduce' => '引薦朋友',
  'do_rm_fans' => '移除粉絲',
  'do_add_blog' => '添加',
  'whisper_att' => '悄悄關注',
  'quit_whisper_att' => '已悄悄關注，取消' ,
  'msg_my_blog' => '自己的博客地址',
  'do_be_att' => '求關注',
  'no_describe' => '還沒填寫個人介紹',
  'more'=>'更多資料>>',
  'description' => '簡介：',
  'no_des' => '暫無介紹。',	
);