<?php
return array (
  'title' => '發出的評論',
  'search_title' => '查找評論內容或評論人',
  'all' => '全部',
  'source_mblog' => '發到微博',
  'source_group' => '發到微群',
  'comment_count' => '共<span node-type="commentNum">%s</span>條',
  'back_to_all_comment' => '返回所有發出的評論',
  'search_result' => '共找到<span>%s</span>條關於“%s”的結果：',
  'comment_to_title' => '以下為我發給%s的全部評論',
  'comment_to_pre' => '你是否要查看：發給',
  'comment_to_suf' => '的評論',
  'no_search_rst' => '沒有找到符合條件的評論',
  'no_comment' => '還沒有評論',
  'reply' => '回覆',
  'de' => '的',
  'me' => '我',
  'comment' => '評論',
  'mblog' => '微博',
  'delete' => '刪除',
  'source' => '來自',
);