<?php
$lang = array(
	'whisper_follow' => '想默默关注一个人，<span class="z_sp">不希望</span>其他人知道？',
	'view_quietfollow_mblog' => '去看看他们最近在说什么' ,
	'whisper_he_now' => '现在你可以悄悄关注他',
	'whisper_by_you' => '被你悄悄关注的人：', 
	'cant_be_recomand'=>'不会收到新粉丝提醒' ,
	'not_in_his_fans'=>'粉丝列表内不会显示你',
	'no_one_knews' => '其他人看你的关注列表，不会显示他',
	'how_to_whisper' => '如何悄悄关注他：',
	'input_nick_up' => '你可以在上方的输入框内，输入对方的昵称，直接悄悄关注他' ,
	'go_his_profile' => '还可以到他的微博页，那里也可以悄悄关注他',
	'you_whisper_follow' => '我悄悄关注了' ,
	'person'	=> '人 ',
	'person_max' => '最多10人',
	'member_level' => '您当前是',
	'member_quite' => '可悄悄关注%s人',
	'add_follow_to_group' => '将关注人添加到分组：',
	'add'	=> '添加',
	'input_nick' => '请输入想要悄悄关注用户的昵称',
	'quit_private_att' => '取消悄悄关注',
	'quiet_follow' => '悄悄关注：',
	'i_know' => '知道了',
);
return $lang ;