<?php
return array(
    'me' => '我',
    'title' => '的游戏',
    'add_game' => '添加新游戏',
    'manage' => '管理',
    'played_start' => '共玩过',
    'played_end' => '个游戏',
    'getachv_start' => '获得',
    'getachv_end' => '个成就',
    'havefriend_start' => '有',
    'havefriend_end' => '个互粉好友',
    'play_none' => '你还没有玩过游戏，',
    'link_add' => '现在就去添加',
    'common_game' => '你们都在玩',
    'he_play_none' => '还没有玩过游戏',
    'all_play' => '可能感兴趣的游戏',
    'user_score' => '%s的成就：',
    'he_playing' => '还玩',
    'friends_playing' => '个互粉在玩',
    'hot_game' => '热门游戏',
    'who_playing' => '等%s个人在玩这个游戏',
    'no_achv' => '无成就系统',
);