<?php
return array(
    'me' => '我',
    'title' => '的遊戲',
    'add_game' => '添加新遊戲',
    'manage' => '管理',
    'played_start' => '共玩過',
    'played_end' => '個遊戲',
    'getachv_start' => '獲得',
    'getachv_end' => '個成就',
    'havefriend_start' => '有',
    'havefriend_end' => '個互粉好友',
    'play_none' => '你還沒有玩過遊戲，',
    'link_add' => '現在就去添加',
    'common_game' => '你們都在玩',
    'he_play_none' => '還沒有玩過遊戲',
    'all_play' => '可能感興趣的遊戲',
    'user_score' => '%s的成就：',
    'he_playing' => '還玩',
    'friends_playing' => '個互粉在玩',
    'hot_game' => '熱門遊戲',
    'who_playing' => '等%s個人在玩這個遊戲',
    'no_achv' => '無成就係統',
);
