<?php
$lang['client'] = '客户端';
$lang['phone_list'] = '对应手机品牌：BlackBerry黑莓';
$lang['blackberry_client'] = '黑莓客户端';
$lang['text_1'] = '基于黑莓系统的黑莓版手机客户端，实现了阅读、发布、评论、转发、私信、关注等各主要功能，支持本地相机即拍即传和新消息提醒。';
$lang['text_2'] = '喜欢微博的你，赶快装上一个<br>开始真正的随时随地“微博”生活吧';
$lang['text_3'] = 'OS前只支持4.7以上的版本<br>用手机访问<a href="#">weibo.cn</a>，进入客户端页面下载手机客户端';
$lang['download_by_type'] = '按型号下载';
$lang['my_berry_number'] = '我的黑莓手机型号';
$lang['download_now'] = '立即下载';
$lang['download_by_platform'] = '按平台下载';
$lang['platform_desc'] = '下载后需要使Desktop Manager帮助你安装到手机';
$lang['client_download'] = '黑莓客户端点击下载';
$lang['style'] = '特点';
$lang['style_1'] = '即拍即发：手机拍照一键发送。';
$lang['style_2'] = '节约流量：数据量更小，最多可节约80%。';
$lang['style_3'] = '多帐号支持：同时添加多个帐号，保存多个帐号信息随心切换。';
$lang['style_4'] = '支持客户端账号注册。';
$lang['style_5'] = '支持4.7OS以上版本的各种机型。';
$lang['style_6'] = '支持TCP直连、WAP、WiFi、BIS、BES等各种类型接入。';
$lang['style_7'] = '可以在情景模式里设置提醒铃声，LED灯，震动等各种方式。';
return $lang;
