<?php
$lang['disable_show'] = "显示错误，请稍后再试。";
$lang['system_error'] = "系统繁忙，请稍候再试吧。";
$lang['operate_failed'] = "操作失败";
$lang['repeated'] = "不要贪心哦，相同内容的东西发一次就够啦。";
$lang['law_not_allow'] = '抱歉，此内容违反了<a target="_blank" href="http://weibo.com/z/guize/guiding.html">《新浪微博社区管理规定(试行)》</a>或相关法规政策，无法发布。如需帮助，请联系<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">微博客服</a>';
$lang['not_follow'] = '你还没有关注此用户';
$lang['remark_self'] = '不能为自己设置备注名哦';
//系统错误码： 此处的报错都以当前行为操作作为报错提醒文案；
$lang['submit_failed'] = '提交失败';
$lang['load_failed'] = '加载失败';
$lang['rumor_not_repost'] = '抱歉，此内容违反了相关法律法规要求，无法发布。<a target="_blank" href="http://help.weibo.com/faq/q/676/12574#12574">查看详情</a>，如需帮助，<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">请联系客服</a>';
$lang['rumor_not_cmt'] = '抱歉，此内容违反了相关法律法规要求，无法发布。<a target="_blank" href="http://help.weibo.com/faq/q/676/12574#12574">查看详情</a>，如需帮助，<a target="_blank" href="http://help.weibo.com/self/query?typeid=1034">请联系客服</a>';
$lang['feed_block_repeat'] = "已经屏蔽了该用户";
$lang['feed_block_error'] = "屏蔽失败";
$lang['feed_block_succ'] = '屏蔽成功';
$lang['feed_block_error_no_followed'] = "您尚未关注此用户，屏蔽失败";
$lang['feed_block_error_max_numm'] = "已经达到屏蔽上限。";
$lang['visible_not_repost'] = '抱歉，不能转发带显示权限的微博';
$lang['visible_not_comment'] = '抱歉，你还没有评论该微博的权限';
$lang['error_params'] = "你提交的内容格式不正确。";
$lang['over_length'] = "糟糕，小秘书数错数啦，删掉几个字试试吧。";
$lang['feed_mid_filtered'] = "隐藏成功";
$lang['filtered_sina_app'] = "该来源暂时不可屏蔽哦。<a href='http://weibo.com/zt/s?k=9286'>我要提建议。</a>";
$lang['filter_app_repeat'] = "已经屏蔽了该应用";
$lang['filter_mid_repeat'] = "已经隐藏了该条微博";
$lang['filter_repeat'] = "已经添加了该屏蔽";
$lang['filter_sina_app'] = "不能屏蔽新浪应用";
$lang['error_create_jxj'] = "最多可创建20个精选集，你已到达上限喽~";
$lang['error_name_exists'] = "您已经有一个相同名字的精选集啦，为你的宝贝儿再起一个名字吧~";
$lang['error_verification'] = '抱歉，请先绑定手机领取"微身份"勋章，帐号更安全。或可继续浏览微博。';
$lang['error_location'] = 'http://weibo.com/z/vshenfen/';
$lang['error_OKText'] = '马上领取';
$lang['error_cancelText'] = '取消';
$lang['error_OKSuda'] = 'key=tblog_identify_stripe&value=badge_apply';
$lang['error_cancelSuda'] = 'key=tblog_identify_stripe&value=identify_cancel';
$lang['error_mblogcard_failed'] = '获取失败！';
$lang['error_mblogcard_none'] = '此微博已不存在！';
return $lang;
