<?php
$lang['client'] = '客戶端'; 
$lang['phone_list'] = '對應手機品牌：蘋果iPhone'; 
$lang['text_1'] = '基於iPhone、iPod touch平台的iPhone版手機客戶端，實現了閱讀、發布、評論、轉發、私信、關注等各主要功能，支持本地相機即拍即傳和新消息提醒，記錄點滴生活，分享精彩瞬間。 '; 
$lang['text_2'] = '記錄點滴生活，分享精彩瞬間。 '; 
$lang['download'] = '點擊按鈕直接訪問APP Store下載應用<br>下載成功後用iTunes同步安裝'; 
$lang['style'] = '特點'; 
$lang['style_1'] = '兩種主題模式：列表模式和氣泡模式。 '; 
$lang['style_2'] = '即拍即發：手機拍照一鍵發送。 '; 
$lang['style_3'] = '節約流量：數據量更小，最多可節約80%。 '; 
$lang['style_4'] = '多帳號支持：同時添加多個帳號，保存多個帳號信息隨心切換。 '; 
$lang['style_5'] = '支持客戶端帳號註冊。 '; 
$lang['style_6'] = '支持iPhone4 Retina 屏幕高清顯示。 '; 
$lang['style_7'] = '支持地理定位。 '; 
$lang['style_8'] = '支持CMNET、CMWAP、WiFi等各種類型接入。 '; 
$lang['style_9'] = '新消息推送功能，將私信實時推送到桌面。 ';
$lang['style_10'] = '新增微博"簽到"功能。 ';
$lang['style_11'] = '設置好友分組。 ';
$lang['style_12'] = '新增@我的、評論篩選功能。 ';
$lang['style_13'] = '支持@聯繫人搜索。 ';
$lang['style_14'] = '查看好友高清頭像。 ';
$lang['style_15'] = '支持多語言切換。 ';
$lang['style_16'] = '微博信息流字號大小設置。 ';
$lang['style_17'] = '支持動態圖內容查看。 ';
$lang['style_18'] = '優化穩定性。 ';
return $lang;
