<?php
return array (
  'repost_to_weibo' => '轉發到微博',
  'repost_to_message' => '轉發到私信',
  'repost_to_qun' => '轉發到微群',
  'repost_as_well' => '同時轉發到我的微博',
  'comment_as_well' => '同時評論給',
  'comment' => '評論',
  'forward' => '轉發',
  'all' => '全部',
  'attentioner' => '關注的人',
  'stranger' => '陌生人',
  'vip' => '認證用戶',
  'common' => '共同評論',
  'no_report' => '無法轉發帶有權限的微博。',
  'attitude' => '表態',
  'text_comment' => '快速評論',
  'no_attitude' => '還沒有人對這條微博表態哦',
  'show_more' => '展開',
  'put_away' => '收起',
);