<?php
/**
 * 缓存的KEY值序号
 */
return array(
    'status' => '1',
    'rt_status' => '2',
    'short_url' => '3',
    'user' => '4',
    'relation' => '5',
    'school' => '6',
    'career' => '7',
    'qun' => '8',
    'pincode' => '9',
    'bubble' => '10',
    'skin' => '11',
    'nav' => '12',
    'comment' => '13',
    'trend' => '14',
    'messages' => '15',
    'tag' => '16',
    'favlist' => '17',
    'privacy' => '18',
    'album' => '19',
    'user_group' => '20',
    'group' => '21',
    'event' => '22',
    'badge' => '23',
    'widget' => '24',
    'guide' => '25',
    'photo' => '26',
    'allinone' => '27',
    'allinone_join' => '28',
    'club' => '29',
    'invite_code' => '30',
    'main'=> '31',
    'account' =>'32',
    'tips'=> '33',
    'myfeed' => '34',
    'module' => '40',
    'feedindex' => '201',
    'cmtindex' => '202',
    'cmtcontent' => '203',
    'hourlytopic' => '42',
    'topic' => '44',
    'setting' => '45',
    'myat' => '46',
    'data' => '47',
    'base' => '48',
    'app' =>'50',
    'version' => '51', //JS/CSS版本号
    'adminlearn' => '52',
    'eps_video' => '53',
    'plaza' => '54',
    'map' => '55',
    'authappkeylist' => '56', //深度合作的第三方应用appkey白名单
    'pay_orders' => '57',
    'active' => '58', //活动微博
    'eps_event' => '59',
    'admintips' => '60', //后台系统设置tips
    'keywords' => '61',
    'register' => '62', //一步注册
    'eps_admin'=> '63', //多账号
    'govmanage' => '64', //政务管理
    'verified'=> '65', //认证信息
    'eps_category' => '66',
    'business_ranking' => '67',
    'platform_photos' => '68', //来自于 微相册 的用户相册数据 
    'package' => '69', //套餐系统的 套餐信息
    'brand' => '70', //品牌
    'epsv5' => '71', //企业微博v5 mps 白名单
    'disclose' => '72',
    'contribute' => '73',
    'widget_bulletin' => '74', //widget 公告缓存
    'app_contact' => '75', //app用户联系信息缓存
    'eps_white' => '76', //企业微博白名单功能
    'eps_backstage' => '77', //baseconf
    'mediapublic' => '78', //媒体公众平台
    'beautypk' => '79', //美颜pk功能存储pk者uid，沈菲添加
    'beautypkresult' => '80', //美颜pk功能存储需要艾特的用户的cache
    'topstatus' => '82', //置顶微博弹层（媒体微博管理中心首页）是否关闭的cache
    'poi' => '83', //位置信息
    'talk' => '84', //访谈缓存
    'recommend_article' => '85', //文章推荐缓存
    'user_status' => '86', //用户状态缓存  目前已有1：群发私信
    'publicplatform_advanced' => '87', //粉丝服务平台-->高级功能缓存
    'management_info' => '88', //媒体微博运营化管理中心
    'style' => '89', //文章多模板
    'publicplatform_message' => '90', //粉丝服务平台-->消息相关缓存
    'doubleegg' => '91',      //双蛋节活动  
    'publicplatform_whitelist' => '92', //粉丝服务平台-->白名单
    'media_order' => '93', //自媒体虚拟物品售卖缓存

    // 新框架下为防止key冲突，每个业务一个统一的key
    'eps' => '500',     //企业
    'media' => '501',   //媒体
    'fanservice' => '502',  //粉服
    'payplatform' => '503', // 付费阅读
);
