<?php 

return array(
	'no status,goto ' => '该分组下没有可以显示的微博，去',
	'add someone?' => '添加几个人到该分组',
	'no feed' => '该公开分组成员还没有发过微博 ',
	'need recommend?goto ' => '想看看还有哪些用户值得关注？推荐你去',
	'to have a try' => '看看',
	'find people ' => '找人',
	'no match, return to ' => '找不到符合条件的微博，返回',
	'all statuses?' => '查看全部微博？',
	'Tips:' => '微博小秘书： 如何快速找到有趣的人？看看小秘书多年总结出的经验吧。',
	'Look for friends:' => '找亲朋好友，查询方式多种多样：',
	'By' => '按',
	'MSN' => 'MSN',
	'mail' => '邮箱',
	'cellphone' => '手机号码',
	'nickname' => '昵称',
	'company' => '公司',
	'school' => '学校',
	'location' => '所在地',
	'etc' => '查找',
	'Lots of famous:' => '找名人，名人堂明星云集：',
	'Entertainment' => '娱乐',
	'Sports' => '体育',
	'Cultural' => '人文',
	'Finance' => '财经',
	'Mass Media' => '传媒',
	'Literature Press' => '文学出版',
	'Radio' => '电台',
	'TV' => '电视台',
	'Institution' => '机构',
	'if complete some info or tweeted,<br />we can invite some people for you' => '只要你填写了标签、学校、公司等个人资料，或者多发几篇微博，<br />我们还能据此推荐你可能感兴趣的人。',
	'go to set account' => '去设置个人资料',
	'you can invite friends to use Weibo, and share life with each other' => '最后你可以邀请你的亲朋好友一起来微博，在这里分享彼此的生活。',
	'go to invite now' => '现在就去邀请',
	'none_quiet_follow' => '你还没有悄悄关注的人呢，',
	'add_quiet_follow' => '快来尝试默默关注一个人的感觉吧。',
	'what_is_quiet_follow' => '什么是<span class="W_fb">悄悄关注</span>' ,
	'quiet_follow_q1' => '悄悄关注是什么？' ,
	'quiet_follow_a1' => '悄悄关注是一种隐形的关注状态',
	'quiet_follow_q2' => '悄悄关注会被人发现吗？' ,
	'quiet_follow_a2' => '不会，除了你自己，没有人知道你在关注他，请放心使用。' ,
	'quiet_follow_a3' => '你悄悄关注的人：他不会收到任何提示，他的粉丝列表中没有你，你的关注列表中也没有他。',
	'feed_overdue_notice1' => '亲，你离开的时间太长啦，请',
	'feed_overdue_notice2' => '点击这里',
	'feed_overdue_notice3' => '重新刷新',
	'mblogsort_prompt1' => '温馨提示',
    'mblogsort_prompt2' => '你正通过智能排序的方式浏览微博，神马是智能排序？马上了解',
    'mblogsort_prompt3' => '太久木有刷微博，不想错过精彩内容？体验智能排序',
    'mblogsort_prompt4' => '微博太多看不过来？不想漏掉重要信息，看看智能排序',
    'step_close' => '关闭',
    'step_next' => '继续',
    'step_end' => '立即使用',
);