<?php
return array(
    'txt_mark' => '標識對比',
    'txt_brand' => '品牌標識組合',
    'txt_sina_brand' => '新浪微博品牌',
    'txt_cnen' => '中英文組合',
    'txt_cn' => '中文組合',
    'txt_en' => '英文組合',
    'txt_format' => '格式',
    'txt_color' => '色彩',
    'color_black' => '單色墨稿',
    'color_white' => '單色反白稿',
    'style_white' => '勾白邊應用形式',
    'style_deep' => '深色底文字反白邊應用形式',
    'btn_normal' => '標準色標識透明背景按鈕' ,
    'btn_white' => '發白標識透明背景按鈕',
    'btn_golden' => '金色浮雕標識透明背景按鈕',
    'txt_btn' => '按鈕',
    'do_preview' => '預覽效果',
    ' do_download' => '下載',
    'color_normal' => '標準色',
    'style_other' => '其他樣式',
    'color_other' => '其他輔助色',
    'wallpaper' => '壁紙',
    'crt_size' => '寸普屏',
    'size' => '寸',
    'color_brand' => '品牌標準色',
    'red' => '紅色',
    'orange' => '橙色',
    'black' => '黑色',
    'txt_usecdc' => '使用規範由新浪微博事業部產品設計中心（Sina Weibo CDC）完成。',
);