<?php
return array(
        'my_invited' => '我邀請註冊的用戶(共%s 人)',
        'title_bilateral' => '已相互關注',
        'add_follow' => '加關注',
        'title_followed' => '已關注',
        'suggest_follow' => '推薦大家關注',
        'he' => '他',
        'she' => '她',
        'advice_binding' => '通知好友綁定手機',
        'is_comming' => '親朋好友正在趕來註冊，耐心等一等。 ',
        'toptip' => '獨樂樂不如眾樂樂<br>快去<a href="/invite/list">邀請朋友</a>加入微博吧',
        'invite_succ' => '活動期間您已成功邀請<a href="#">%s位</a> 好友',
        'enter_zt' => '參加抽獎活動',
        'invite_by_mobile' => '通過短信邀請',
        'invite_by_link' => '通過鏈接邀請',
        'invite_by_pic' => '通過微白板邀請',
        'invite_by_msn' => '通過MSN/郵箱邀請',
        'recommand_title' => '把 %s 推薦給朋友',
        'recommand_content' => '快來看看@%s 的微博',
        'recommand_info' => '說說推薦理由吧',
        'notice_title' => '通知好友綁定手機，雙方獲得抽獎機會。 ',
        'notice_content' => '@%s 快去綁定手機吧，綁定後，我們都可以抽獎。 http://account.weibo.com/set/mobile',
        'notice_info' => '通知好友綁定手機'
);
